GET http://127.0.0.1:8000/api/products/ HTTP/1.1

###

POST http://127.0.0.1:8000/api/products/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzUwOTU2NTk2LCJpYXQiOjE3NTA5NTYyOTYsImp0aSI6ImY1Njk2N2ZiMmY4OTRkN2RhNjg0YWYzMDRkMWZjY2MyIiwidXNlcl9pZCI6Mn0.GQ3YOae1c0_O5SplTHx8bWeNVk-jzddd6fGYHZkTNoI

{
    "name": "Drone",
    "price": 80000.00,
    "stock": 10,
    "description": "Do Fly with Drone"
}

###

GET http://127.0.0.1:8000/api/user-orders/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzUwOTU3MTc2LCJpYXQiOjE3NTA5NTY4NzYsImp0aSI6IjhiYWIwMTdmZDJjODRkYTQ5M2JlZmU1NDg5MmIyMzVkIiwidXNlcl9pZCI6Mn0.aOPKI7uB3Lwjrurq78sBTf5CeG03oixzLHLyUiv4wLk


###

GET http://127.0.0.1:8000/api/products/4/ HTTP/1.1


###
PUT http://127.0.0.1:8000/api/products/4/ HTTP/1.1
Content-Type: application/json

{
    "name": "Enfield",
    "price": 10000.00,
    "stock": 10,
    "description": "Ride nd Rocks"
}

###

DELETE  http://127.0.0.1:8000/api/products/4/ HTTP/1.1

###

GET http://127.0.0.1:8000/api/orders/de1d6ce3-1927-4b73-9c2e-92d6bf2e9507/ HTTP/1.1 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzUxODk3NzIyLCJpYXQiOjE3NTE4OTc0MjIsImp0aSI6IjQyN2JlY2YzMWIxZTQ3MTBhYjFhZGRkZmI1N2FiZmZlIiwidXNlcl9pZCI6Mn0.4J5OPhTRIdSKnQP_UkEFhPCuX1dcMophSuVljCceJXo

###

POST http://127.0.0.1:8000/api/orders/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzUyMDAwMTkyLCJpYXQiOjE3NTE5OTk4OTIsImp0aSI6IjJkMDk2OGJkMjc0NTQ4MDFiOGMyNWUwMWM2OWQyMGM0IiwidXNlcl9pZCI6Mn0.QJeef3GpyjA94jlZDHIVE5BJY4A-r13_DHRsCsnibr4
Content-Type: application/json

{
    "status" : "Pending",
    "items": [
        {
            "product": 2,
            "quantity": 2
        },
        {
            "product": 3,
            "quantity": 1
        }
    ]
}

###

PUT http://127.0.0.1:8000/api/orders/bc4c4b64-d25e-4577-80bc-185ebdc9a238/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzUyMDAyNzM4LCJpYXQiOjE3NTIwMDI0MzgsImp0aSI6IjE0MzE2ZDM5MjM4ZDQ3ZTI5ZWE1YzhkZTY2ODY2ZmM3IiwidXNlcl9pZCI6Mn0.8Lh9sPpmsV_9YSl82zlThcHLaIwbWTpEukYFvOhM-eQ
Content-Type: application/json

{
    "status" : "Pending",
    "items": [
        {
            "product": 5,
            "quantity": 3
        },
        {
            "product": 4,
            "quantity": 1
        }
    ]
}

###

POST http://127.0.0.1:8000/api/token/ HTTP/1.1
Content-Type: application/json

{
    "username" : "abunaim",
    "password" : "abunaim"
}

###
