GET http://127.0.0.1:8000/api/products/ HTTP/1.1

###

POST http://127.0.0.1:8000/api/products/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzUwOTU2NTk2LCJpYXQiOjE3NTA5NTYyOTYsImp0aSI6ImY1Njk2N2ZiMmY4OTRkN2RhNjg0YWYzMDRkMWZjY2MyIiwidXNlcl9pZCI6Mn0.GQ3YOae1c0_O5SplTHx8bWeNVk-jzddd6fGYHZkTNoI

{
    "name": "Drone",
    "price": 80000.00,
    "stock": 10,
    "description": "Do Fly with Drone"
}

###

GET http://127.0.0.1:8000/api/products/4/ HTTP/1.1

###
PUT http://127.0.0.1:8000/api/products/4/ HTTP/1.1
Content-Type: application/json

{
    "name": "Enfield",
    "price": 10000.00,
    "stock": 10,
    "description": "Ride nd Rocks"
}

###

DELETE  http://127.0.0.1:8000/api/products/4/ HTTP/1.1

###

GET http://127.0.0.1:8000/api/orders/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzUyNTY0Njk4LCJpYXQiOjE3NTI1NjEwOTgsImp0aSI6IjgyMGQ4NTMzNTQ0MDQxYTM5ZTFiN2YyZDU1YzgxZDdlIiwidXNlcl9pZCI6Mn0.bU5uvbEQCY458Lvq9NoGyLESwLst79WVsiLHry9ayAk

###

POST http://127.0.0.1:8000/api/orders/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzUyMDAwMTkyLCJpYXQiOjE3NTE5OTk4OTIsImp0aSI6IjJkMDk2OGJkMjc0NTQ4MDFiOGMyNWUwMWM2OWQyMGM0IiwidXNlcl9pZCI6Mn0.QJeef3GpyjA94jlZDHIVE5BJY4A-r13_DHRsCsnibr4
Content-Type: application/json

{
    "status" : "Pending",
    "items": [
        {
            "product": 2,
            "quantity": 2
        },
        {
            "product": 3,
            "quantity": 1
        }
    ]
}

###

POST http://127.0.0.1:8000/api/orders/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzUyNzQ1NjE5LCJpYXQiOjE3NTI3NDIwMTksImp0aSI6IjJjZTc1NTlmOGVmZjQzYWNiYzhjYTVhZGIyYjM3NDJjIiwidXNlcl9pZCI6M30.mVqiD5-eHvX4Yu03ssmtRolsL0qm81QVWTHzGa7OPsc
Content-Type: application/json

{
    "status" : "Pending",
    "items": [
        {
            "product": 5,
            "quantity": 3
        },
        {
            "product": 4,
            "quantity": 1
        }
    ]
}

###

POST http://127.0.0.1:8000/api/token/ HTTP/1.1
Content-Type: application/json

{
    "username" : "admin1",
    "password" : "admin1"
}

###

POST http://127.0.0.1:8000/auth/jwt/create/ HTTP/1.1
Content-Type: application/json

{
    "username" : "admin1",
    "password" : "admin1"
}

###

GET http://127.0.0.1:8000/auth/users/me/ HTTP/1.1
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzUyODYzNjA3LCJpYXQiOjE3NTI4NjAwMDcsImp0aSI6ImEwNjU4ZDRkOTZjYjQ2NjJiZjdmMzlhNGVmNmY3NGY3IiwidXNlcl9pZCI6Mn0.JhbPOr7Q2Wl2Lr71X1wS3MkM-9ajZSeon-Pt0Nd8HfE

###
POST http://127.0.0.1:8000/auth/jwt/refresh/ HTTP/1.1
Content-Type: application/json

{
    "refresh" : "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc1Mjk0Njc5OCwiaWF0IjoxNzUyODYwMzk4LCJqdGkiOiJhZGVhMmM5ZjRmMWE0YzdmYjZmNDFhNjc5ZDY2MGEzYiIsInVzZXJfaWQiOjN9.W9wqfKOepbL1TcirODGMeyp5t5lFcTdCjQ14ErBAPVQ"
}
